name: react-native-android-build-apk
on: workflow_dispatch

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          cd HotScrew
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          cd HotScrew
          npm install
      - name: Build Android Release
        run: |
          cd HotScrew/android
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon    
      - name: Sign App Bundle
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
         releaseDirectory: HotScrew/android/app/build/outputs/apk/release
         signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
         alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
         keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
         keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}    
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
         name: Signed App Bundle
         path: ${{steps.sign_app.outputs.signedReleaseFile}}
